package brokerproperties

import (
	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

var _ = Describe("SecurityConfigData", func() {
	It("includes the login.config URL pointing to the mount path", func() {
		data := string(SecurityConfigData("/amq/secrets/my-props"))
		Expect(data).To(ContainSubstring("login.config.url.1=file:/amq/secrets/my-props/login.config"))
	})

	It("includes both PEM security providers", func() {
		data := string(SecurityConfigData("/amq/secrets/my-props"))
		Expect(data).To(ContainSubstring("security.provider.13=de.dentrassi.crypto.pem.PemKeyStoreProvider"))
		Expect(data).To(ContainSubstring("fips.provider.8=de.dentrassi.crypto.pem.PemKeyStoreProvider"))
	})

	It("starts with a # comment header", func() {
		data := string(SecurityConfigData("/path"))
		Expect(data).To(HavePrefix("# generated by crd"))
	})
})

var _ = Describe("LoginConfigData", func() {
	It("opens with the realm name", func() {
		data := string(LoginConfigData("myRealm", "/amq/secrets/props", "users.properties", "roles.properties"))
		Expect(data).To(ContainSubstring("myRealm {"))
	})

	It("includes the TextFileCertificateLoginModule", func() {
		data := string(LoginConfigData("myRealm", "/amq/secrets/props", "users.properties", "roles.properties"))
		Expect(data).To(ContainSubstring("TextFileCertificateLoginModule required"))
	})

	It("sets the certUsersKey for textfiledn.user", func() {
		data := string(LoginConfigData("myRealm", "/path", "my-users.properties", "my-roles.properties"))
		Expect(data).To(ContainSubstring("org.apache.activemq.jaas.textfiledn.user=my-users.properties"))
	})

	It("sets the certRolesKey for textfiledn.role", func() {
		data := string(LoginConfigData("myRealm", "/path", "my-users.properties", "my-roles.properties"))
		Expect(data).To(ContainSubstring("org.apache.activemq.jaas.textfiledn.role=my-roles.properties"))
	})

	It("sets the baseDir to the mount path root", func() {
		data := string(LoginConfigData("myRealm", "/amq/secrets/props", "u", "r"))
		Expect(data).To(ContainSubstring(`baseDir="/amq/secrets/props"`))
	})

	It("uses // as the comment character", func() {
		data := string(LoginConfigData("myRealm", "/path", "u", "r"))
		Expect(data).To(HavePrefix("// generated by crd"))
	})
})

var _ = Describe("BrokerCertUsersData", func() {
	It("includes the hardcoded hawtio entry", func() {
		data := string(BrokerCertUsersData("op-cn", "operand-cn", ""))
		Expect(data).To(ContainSubstring("hawtio=/CN = hawtio-online"))
	})

	It("includes the operator CN in a regex pattern", func() {
		data := string(BrokerCertUsersData("my-operator", "my-operand", ""))
		Expect(data).To(ContainSubstring("operator=/.*my-operator.*/"))
	})

	It("includes the operand CN as the probe entry", func() {
		data := string(BrokerCertUsersData("op", "my-operand", ""))
		Expect(data).To(ContainSubstring("probe=/.*my-operand.*/"))
	})

	It("includes the prometheus CN when non-empty", func() {
		data := string(BrokerCertUsersData("op", "operand", "my-prometheus"))
		Expect(data).To(ContainSubstring("prometheus=/.*my-prometheus.*/"))
	})

	It("omits the prometheus entry when prometheusCN is empty", func() {
		data := string(BrokerCertUsersData("op", "operand", ""))
		Expect(data).NotTo(ContainSubstring("prometheus="))
	})
})

var _ = Describe("BrokerCertRolesData", func() {
	It("assigns status to operator and probe", func() {
		data := string(BrokerCertRolesData())
		Expect(data).To(ContainSubstring("status=operator,probe"))
	})

	It("assigns metrics to operator and prometheus", func() {
		data := string(BrokerCertRolesData())
		Expect(data).To(ContainSubstring("metrics=operator,prometheus"))
	})

	It("assigns hawtio to hawtio", func() {
		data := string(BrokerCertRolesData())
		Expect(data).To(ContainSubstring("hawtio=hawtio"))
	})

	It("produces the same bytes on every call", func() {
		Expect(BrokerCertRolesData()).To(Equal(BrokerCertRolesData()))
	})
})

var _ = Describe("JolokiaConfigData", func() {
	It("sets protocol to https", func() {
		data := string(JolokiaConfigData("/ca/path", "/cert/path", "/key/path"))
		Expect(data).To(ContainSubstring("protocol=https"))
	})

	It("sets the caCert to the provided path", func() {
		data := string(JolokiaConfigData("/ca/path/ca.crt", "/cert/path", "/key/path"))
		Expect(data).To(ContainSubstring("caCert=/ca/path/ca.crt"))
	})

	It("sets serverCert to the provided path", func() {
		data := string(JolokiaConfigData("/ca", "/secrets/broker/tls.crt", "/key"))
		Expect(data).To(ContainSubstring("serverCert=/secrets/broker/tls.crt"))
	})

	It("sets serverKey to the provided path", func() {
		data := string(JolokiaConfigData("/ca", "/cert", "/secrets/broker/tls.key"))
		Expect(data).To(ContainSubstring("serverKey=/secrets/broker/tls.key"))
	})

	It("enables mutual TLS client authentication", func() {
		data := string(JolokiaConfigData("/ca", "/cert", "/key"))
		Expect(data).To(ContainSubstring("useSslClientAuthentication=true"))
	})

	It("binds to port 8778", func() {
		data := string(JolokiaConfigData("/ca", "/cert", "/key"))
		Expect(data).To(ContainSubstring("port=8778"))
	})
})

var _ = Describe("PemCfgData", func() {
	It("includes source.key at the provided path", func() {
		data := string(PemCfgData("", "/secrets/broker/tls.key", "/secrets/broker/tls.crt"))
		Expect(data).To(ContainSubstring("source.key=/secrets/broker/tls.key"))
	})

	It("includes source.cert at the provided path", func() {
		data := string(PemCfgData("", "/secrets/broker/tls.key", "/secrets/broker/tls.crt"))
		Expect(data).To(ContainSubstring("source.cert=/secrets/broker/tls.crt"))
	})

	It("includes the alias line when alias is non-empty", func() {
		data := string(PemCfgData("alias", "/key", "/cert"))
		Expect(data).To(ContainSubstring("alias=alias"))
	})

	It("omits the alias line when alias is empty", func() {
		data := string(PemCfgData("", "/key", "/cert"))
		Expect(data).NotTo(ContainSubstring("alias="))
	})
})

var _ = Describe("BrokerPrometheusConfigData", func() {
	It("includes the SSL keyStore pointing to the pemcfg path", func() {
		data := string(BrokerPrometheusConfigData("/path/_cert.pemcfg", "/ca/trust", "my-broker"))
		Expect(data).To(ContainSubstring("filename: /path/_cert.pemcfg"))
		Expect(data).To(ContainSubstring("type: PEMCFG"))
	})

	It("includes the trustStore pointing to the CA path", func() {
		data := string(BrokerPrometheusConfigData("/pem", "/amq/secrets/ca/ca.crt", "my-broker"))
		Expect(data).To(ContainSubstring("filename: /amq/secrets/ca/ca.crt"))
		Expect(data).To(ContainSubstring("type: PEMCA"))
	})

	It("includes the broker name in includeObjectNames", func() {
		data := string(BrokerPrometheusConfigData("/pem", "/ca", "my-broker"))
		Expect(data).To(ContainSubstring(`broker="my-broker"`))
	})

	It("includes rules for TotalMessageCount, TotalMessagesAdded, and TotalMessagesAcknowledged", func() {
		data := string(BrokerPrometheusConfigData("/pem", "/ca", "my-broker"))
		Expect(data).To(ContainSubstring("artemis_total_pending_message_count"))
		Expect(data).To(ContainSubstring("artemis_total_consumed_message_count"))
		Expect(data).To(ContainSubstring("artemis_total_produced_message_count"))
	})

	It("enables lowercase output names", func() {
		data := string(BrokerPrometheusConfigData("/pem", "/ca", "my-broker"))
		Expect(data).To(ContainSubstring("lowercaseOutputName: true"))
		Expect(data).To(ContainSubstring("lowercaseOutputLabelNames: true"))
	})
})

var _ = Describe("ServicePrometheusConfigData", func() {
	It("includes the SSL keyStore and trustStore", func() {
		data := string(ServicePrometheusConfigData("/path/_cert.pemcfg", "/ca/trust", "svc", nil))
		Expect(data).To(ContainSubstring("filename: /path/_cert.pemcfg"))
		Expect(data).To(ContainSubstring("filename: /ca/trust"))
	})

	It("uses attrNameSnakeCase instead of lowercaseOutputName", func() {
		data := string(ServicePrometheusConfigData("/pem", "/ca", "svc", nil))
		Expect(data).To(ContainSubstring("attrNameSnakeCase: true"))
		Expect(data).NotTo(ContainSubstring("lowercaseOutputName"))
	})

	It("includes queue-level includeObjectNameAttributes when appQueues is non-empty", func() {
		queues := map[string]bool{"MY.QUEUE": true}
		data := string(ServicePrometheusConfigData("/pem", "/ca", "svc", queues))
		Expect(data).To(ContainSubstring("includeObjectNameAttributes:"))
		Expect(data).To(ContainSubstring("MY.QUEUE"))
	})

	It("omits includeObjectNameAttributes when appQueues is empty", func() {
		data := string(ServicePrometheusConfigData("/pem", "/ca", "svc", nil))
		Expect(data).NotTo(ContainSubstring("includeObjectNameAttributes:"))
	})

	It("routes multicast addresses (with ::) to multicast routing-type", func() {
		queues := map[string]bool{"MY.TOPIC::MY.SUBSCRIPTION": true}
		data := string(ServicePrometheusConfigData("/pem", "/ca", "svc", queues))
		Expect(data).To(ContainSubstring(`routing-type="multicast"`))
		Expect(data).To(ContainSubstring(`address="MY.TOPIC"`))
		Expect(data).To(ContainSubstring(`queue="MY.SUBSCRIPTION"`))
	})

	It("routes plain addresses (no ::) to anycast routing-type", func() {
		queues := map[string]bool{"MY.QUEUE": true}
		data := string(ServicePrometheusConfigData("/pem", "/ca", "svc", queues))
		Expect(data).To(ContainSubstring(`routing-type="anycast"`))
		Expect(data).To(ContainSubstring(`address="MY.QUEUE"`))
	})

	It("produces queue attributes in deterministic order", func() {
		queues := map[string]bool{"B.QUEUE": true, "A.QUEUE": true}
		first := string(ServicePrometheusConfigData("/pem", "/ca", "svc", queues))
		second := string(ServicePrometheusConfigData("/pem", "/ca", "svc", queues))
		Expect(first).To(Equal(second))
		Expect(first).To(ContainSubstring("A.QUEUE"))
		aIdx := indexOfString(first, "A.QUEUE")
		bIdx := indexOfString(first, "B.QUEUE")
		Expect(aIdx).To(BeNumerically("<", bIdx))
	})

	It("includes the broker_queue rules pattern", func() {
		data := string(ServicePrometheusConfigData("/pem", "/ca", "svc", nil))
		Expect(data).To(ContainSubstring("broker_queue_$5"))
	})
})

func indexOfString(s, substr string) int {
	for i := 0; i <= len(s)-len(substr); i++ {
		if s[i:i+len(substr)] == substr {
			return i
		}
	}
	return -1
}
